spring:
    application:
      name: dontknowhatodo

    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: ${JPA_DDL_AUTO}
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    graphql:
      graphiql:
        enabled: ${GRAPHIQL_ENABLED}

    security:
      oauth2:
        client:
          registration:
            google:
              clientId: ${GOOGLE_CLIENT_ID}
              clientSecret: ${GOOGLE_CLIENT_SECRET}
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            # facebook:
            #   clientId: ${FACEBOOK_CLIENT_ID}
            #   clientSecret: ${FACEBOOK_CLIENT_SECRET}
            #   redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            #   scope:
            #     - email
            #     - public_profile
            # github:
            #   clientId: ${GITHUB_CLIENT_ID}
            #   clientSecret: ${GITHUB_CLIENT_SECRET}
            #   redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            #   scope:
            #     - user:email
            #     - read:user
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
application:
  profile: ${PROFILE}
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
    cors:
      allowedOrigins: 
        - ${FRONTEND_URL}
    oauth2:
      authorizedRedirectUris:
        - ${FRONTEND_REDIRECT_URI}
